### ISSUE TITLE
Question about Dist.1 / 2

### ISSUE THREAD

**Issue by zhliu0106** [songhaoyu/BoB#7]
When I run the evaluation script:

'''
CUDA_VISIBLE_DEVICES=0 python bertoverbert.py --dumped_token ./data/ConvAI2/convai2_tokenized/ \
 --dataset_type convai2 \
 --encoder_model ./pretrained_models/bert/bert-base-uncased/  \
 --do_evaluation --do_predict \
 --eval_epoch 7
'''
The results are shown below:
Distinct-1 (hypothesis, hypothesis_2, reference): 0.0442, 0.0393, 0.1048
Distinct-2 (hypothesis, hypothesis_2, reference): 0.162, 0.1362, 0.4824

why the Dist.1/2 of hypothesis_2 (3.93, 13.62) can not reach the number in Table 3 (8.40, 36.08)? 
or how should I set the argument to obtain the result in Table 3?

Thanks!

**Comment by haoyusoong** [comment]
You should choose a better checkpoint rather than just use `--eval_epoch 7`, as the training variance could considerably affect the results.

**Comment by zhliu0106** [comment]
Thanks for your reply

**Comment by Wenze7** [comment]
> Thanks for your reply

Hi~ bro! Do you solve this problem? I want to know can I obtain the result by simply change the epoch?

**Comment by Fang-git0** [comment]
> Thanks for your reply

Do you solve this problem?  I can't obtain the same distinct, (epoch 19)
